### ISSUE TITLE
PreComp crashes with 4th shear web

### ISSUE THREAD

**Issue by evan-gaertner** [WISDEM/RotorSE#10]
I've been trying to perform RotorSE analysis on the DTU 10MW, which has 3 shear webs and an flat trailing edge, i.e. 4 shear webs for PreComp.  PreComp was crashing at the first span location with all 4 webs during the 'seg_info' subroutine.  In PreCompPy.f90, the dimension for several variables were set to "n_af_nodes+20", which is one too small in the case of 4 webs.  Increasing this and recompiling resolved the issue.

**Comment by dykesk** [comment]
@even-gaertner thanks for that suggestion - we'd be happy to have your contribution back if you want to do a pull-request for the change; or if you want, just send the code snippet you'd like to see adapted to @andrewning
